MyBloggingRazorPage/Models/Article.cs
using System;

namespace MyBloggingRazorPage.Models
{
    public class Article
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string ImageAlt { get; set; }
        public string ImageTitle { get; set; }
        public string ShortDescription { get; set; }
        public string Body { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime CreationDate { get; set; }

        public Article(string title, string image
            , string imageAlt, string imageTitle, string shortDescription, string body)
        {
            Title = title;
            Image = image;
            ImageAlt = imageAlt;
            ImageTitle = imageTitle;
            ShortDescription = shortDescription;
            Body = body;
            CreationDate = DateTime.Now;
            IsDeleted = false;
        }
    }
}

MyBloggingRazorPage/Models/ArticleViewModel.cs
using System;

namespace MyBloggingRazorPage.Models
{
    public class ArticleViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string ImageAlt { get; set; }
        public string ImageTitle { get; set; }
        public string ShortDescription { get; set; }
        public string Body { get; set; }
        public string CreationDate { get; set; }
    }
}

MyBloggingRazorPage/Models/CreateArticle.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MyBloggingRazorPage.Models
{
    public class CreateArticle
    {
        [DisplayName("عنوان")]
        [Required(ErrorMessage = "لطفا عنوان را وارد کنید.")]
        [MinLength(5,ErrorMessage = "عنوان شما باید حداقل 15 حرف داشته باشد")]
        [MaxLength(255,ErrorMessage = "عنوان شما نمیتواند بیشتر از 255 حرف داشته باشد.")]
        public string Title { get; set; }
        [Required(ErrorMessage = "لطفا عکس را وارد کنید.")]
        [DisplayName("مسیر عکس")]
        public string Image { get; set; }
        [Required(ErrorMessage = "لطفا Alt عکس را وارد کنید.")]
        [DisplayName("Alt عکس")]
        public string ImageAlt { get; set; }
        [Required(ErrorMessage = "لطفا عنوان عکس را وارد کنید.")]
        [DisplayName("عنوان عکس")]
        public string ImageTitle { get; set; }
        [Required(ErrorMessage = "لطفا توضیحات کوتاه مقاله را وارد کنید.")]
        [DisplayName("توضیحات کوتاه")]
        public string ShortDescription { get; set; }
        [Required(ErrorMessage = "لطفا متن مقاله را وارد کنید.")]
        [DisplayName("متن مقاله")]
        public string Body { get; set; }
    }
}

MyBloggingRazorPage/Pages/ArticleDetails.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyBloggingRazorPage.Models;

namespace MyBloggingRazorPage.Pages
{
    public class ArticleDetailsModel : PageModel
    {
        public ArticleViewModel Article { get; set; }
        private readonly BlogContext _context;

        public ArticleDetailsModel(BlogContext context)
        {
            _context = context;
        }
        public void OnGet(int id)
        {
            Article = _context.Articles.Select(x => new ArticleViewModel
            {
                Id = x.Id,
                Body = x.Body,
                Image = x.Image,
                ImageAlt = x.ImageAlt,
                Title = x.Title
                
            }).FirstOrDefault(x => x.Id == id);
        }
    }
}

MyBloggingRazorPage/Pages/CreateNewArticle.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyBloggingRazorPage.Models;

namespace MyBloggingRazorPage.Pages
{
    public class CreateNewArticleModel : PageModel
    {
        private readonly BlogContext _context;
        public CreateArticle Command { get; set; }
        [TempData]
        public string ErrorMessage { get; set; }

        public CreateNewArticleModel(BlogContext context)
        {
            _context = context;
        }
        public void OnGet()
        {
        }

        public IActionResult OnPost(CreateArticle command)
        {
            if (!ModelState.IsValid)
            {
                ErrorMessage = "لطفا اطلاعات خواسته شده را وارد کنید.";
                return Page();
            }
            else
            {
                var article = new Article(command.Title, command.Image, command.ImageAlt, command.ImageTitle,
                    command.ShortDescription, command.Body);
                _context.Articles.Add(article);
                _context.SaveChanges();
                return RedirectToPage("./Index");

            }
        }
    }
}

MyBloggingRazorPage/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MyBloggingRazorPage.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MyBloggingRazorPage/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using MyBloggingRazorPage.Models;

namespace MyBloggingRazorPage.Pages
{
    public class IndexModel : PageModel
    {
        public List<ArticleViewModel> Articles { get; set; }
        private readonly BlogContext _context;

        public IndexModel(BlogContext context)
        {
            _context = context;
        }

        public IActionResult OnGetDeleted(int id)
        {
            var article = _context.Articles.First(x => x.Id == id);
            article.IsDeleted = true;
            _context.SaveChanges();
            return RedirectToPage("./Index");
        }
        public void OnGet()
        {
            Articles = _context.Articles.Where(x => x.IsDeleted == false)
                .Select(x => new ArticleViewModel
                {
                    Id = x.Id,
                    Body = x.Body,
                    ShortDescription = x.ShortDescription,
                    Image = x.Image,
                    ImageAlt = x.ImageAlt,
                    ImageTitle = x.ImageTitle,
                    CreationDate = x.CreationDate.ToString(),
                    Title = x.Title
                }).ToList();
        }
    }
}

MyBloggingRazorPage/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBloggingRazorPage.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MyBloggingRazorPage/Pages/ArticleDetails.cshtml
@page "{id:int}"
@model MyBloggingRazorPage.Pages.ArticleDetailsModel
@{
}
<div class="col-12 mb-3">
    <h1>@Model.Article.Title</h1>
</div>
<div class="col-12 mb-3">
    <img src="./images/@Model.Article.Image" alt="@Model.Article.ImageAlt" title="@Model.Article.ImageTitle" class="img-fluid">
</div>
<div class="col-12">
    <p class="article-content">
        @Model.Article.Body
    </p>
</div>

MyBloggingRazorPage/Pages/CreateNewArticle.cshtml
@page
@model MyBloggingRazorPage.Pages.CreateNewArticleModel
@{
    ViewData["Title"] = "ایجاد مقاله ی جدید";
}
<div class="col-12">
    @if (@Model.ErrorMessage != null)
    {
        <div class="alert alert-danger">
            @Model.ErrorMessage
        </div>
    }
    <div class="col-6 mr-auto ml-auto text-center">
        <h1 class="border-bottom mb-3 text-primary">ایجاد مقاله ی جدید</h1>
    </div>
</div>
<form class="mr-auto ml-auto" method="post">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="@Model.Command.Title"></label>
            <input class="form-control" asp-for="@Model.Command.Title">
            <span class="text-danger" asp-validation-for="@Model.Command.Title"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="@Model.Command.Image"></label>
            <input class="form-control" asp-for="@Model.Command.Image">
            <span class="text-danger" asp-validation-for="@Model.Command.Image"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="@Model.Command.ImageAlt"></label>
            <input class="form-control" asp-for="@Model.Command.ImageAlt">
            <span class="text-danger" asp-validation-for="@Model.Command.ImageAlt"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="@Model.Command.ImageTitle"></label>
            <input class="form-control" asp-for="@Model.Command.ImageTitle">
            <span class="text-danger" asp-validation-for="@Model.Command.ImageTitle"></span>
        </div>
        <div class="form-group col-md-12">
            <label asp-for="@Model.Command.ShortDescription"></label>
            <textarea class="form-control" asp-for="@Model.Command.ShortDescription"></textarea>
            <span class="text-danger" asp-validation-for="@Model.Command.ShortDescription"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Command.Body"></label>
        <textarea rows="5" type="text" class="form-control" asp-for = "@Model.Command.Body"></textarea>
        <span class="text-danger" asp-validation-for="@Model.Command.Body"></span>
    </div>
    <button type="submit" class="btn btn-success">ارسال</button>
</form>

MyBloggingRazorPage/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "صفحه اصلی";
}

<div class="col-12 mb-3">
    <div class="row">
        <div class="border-bottom col-3 ml-auto mr-auto text-center">
            <h2>تازه ترین مقالات</h2>
        </div>
    </div>
</div>
@foreach (var item in Model.Articles)
{
    <div class="col-4 mb-2">
        <div class="card">
            <img src="~/images/@item.Image" class="card-img-top" alt="@item.ImageAlt">
            <div class="card-body">
                <h5 class="card-title">@item.ImageTitle</h5>
                <p class="card-text">
                    @item.ShortDescription
                </p>
                <a asp-page="./ArticleDetails" asp-route-id="@item.Id" class="btn btn-info">ادامه مطلب</a>
                <a asp-page-handler="Deleted" asp-route-id="@item.Id" class="btn btn-danger">حذف مقاله</a>
            </div>
        </div>
    </div>
}

MyBloggingRazorPage/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>پروژه بلاگری شاهین | @ViewData["Title"]</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" href="~/style.css">
</head>

<body class="dir-rtl">

    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-info bg-dark">
            <a class="navbar-brand" href="https://zamanishahin.github.io" target="_blank">RazorPages</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-page="/Index">صفحه اصلی <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-page="/CreateNewArticle">ایجاد مقاله</a>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">آموزش Razor Pages</h1>
                <p class="lead text-dark">
                    وبسایت وبلاگ شخصی شاهین زمانی | در این پروژه یک پروژه ی ساده ی وب بلاگینگ پیاده سازی شده است
                </p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            @RenderBody()
        </div>
    </div>
    <footer class="bg-dark mt-5">
        <div class="text-center text-light py-3">
            پروژه ی شخصی
            <a href="https://zamanishahin.github.io" target="_blank">شاهین زمانی</a>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    </script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @RenderSection("Scripts",false)

</body>

</html>